{
 "title": "HP iLO Status",
 "tags": [ "hpilo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Uplink",
    "label": "Uplink",
    "query": {
     "query": "label_values(hpilo_firmware_version,Uplink)"
    }
   },
   {
    "name": "server_name",
    "label": "Server",
    "query": {
     "query": "label_values(hpilo_firmware_version{Uplink=\"$Uplink\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{instance=~\"$server_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power consumtion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(hpilo_power_supplies_readings{instance=\"$server_name\"}[$__range]) / (count_over_time(hpilo_power_supplies_readings{istance=\"$server_name\"}[1m]) * 60) / 1000",
     "legendFormat": "Power"
    },
    {
     "expr": "sum_over_time(hpilo_power_supplies_readings{instance=\"$server_name\"}[$__range]) / (count_over_time(hpilo_power_supplies_readings{instance=\"$server_name\"}[1m]) * 60) / 1000 * 2000",
     "legendFormat": "Estimated money"
    }
   ]
  },
  {
   "title": "Power reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_power_supplies_readings{instance=\"$server_name\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Power reading",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(hpilo_power_supplies_readings{instance=~\"$server_name\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Server hardware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{instance=\"$server_name\"}",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "iLO version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{instance=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hpilo_temperature_value{instance=\"$server_name\"}) by (sensor)",
     "legendFormat": "{{instance}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Overall health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_battery_status{instance=\"$server_name\"}",
     "legendFormat": "Battery"
    },
    {
     "expr": "hpilo_storage_status{instance=\"$server_name\"}",
     "legendFormat": "Storage"
    },
    {
     "expr": "hpilo_fans_status{instance=\"$server_name\"}",
     "legendFormat": "Fans"
    },
    {
     "expr": "hpilo_bios_hardware_status{instance=\"$server_name\"}",
     "legendFormat": "Hardware"
    },
    {
     "expr": "hpilo_memory_status{instance=\"$server_name\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "hpilo_power_supplies_status{instance=\"$server_name\"}",
     "legendFormat": "Power Supplies"
    },
    {
     "expr": "hpilo_processor_status{instance=\"$server_name\"}",
     "legendFormat": "Processor"
    },
    {
     "expr": "hpilo_network_status{instance=\"$server_name\"}",
     "legendFormat": "Network"
    },
    {
     "expr": "hpilo_temperature_status{instance=\"$server_name\"}",
     "legendFormat": "Temperatures"
    },
    {
     "expr": "hpilo_vrm_status{instance=\"$server_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_fan_speed{instance=\"$server_name\"}) by (fan)",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_memory_detail{instance=\"$server_name\"})",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Memory speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, hpilo_memory_detail{instance=\"$server_name\"})",
     "legendFormat": "{{operating_frequency}}"
    }
   ]
  },
  {
   "title": "PSU status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_power_supply_status{capacity_w!=\"0\", instance=\"$server_name\",ps!~\"Battery.*\"}) by (ps, capacity_w)",
     "legendFormat": "{{ps}} - {{capacity_w}} W"
    }
   ]
  },
  {
   "title": "CPU name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, hpilo_processor_detail{instance=\"$server_name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU socket",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpilo_processor_detail{instance=\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fans health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_fan_status{instance=\"$server_name\"}",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "PSU status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_power_supply_status{instance=\"$server_name\",ps!~\"Battery.*\"}",
     "legendFormat": "{{ps}}"
    }
   ]
  },
  {
   "title": "storagehealth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_storage_pd_health_status{instance=\"$server_name\"}",
     "legendFormat": "{{physical_drive}}"
    }
   ]
  }
 ]
}